function Transparency(groups)
    for _, group in ipairs(groups) do
        vim.api.nvim_set_hl(0, group, { bg = "none" })
    end
end

Transparency({
    "Normal",
    "NormalNC",
    "NormalFloat",
    "SignColumn",
    "EndOfBuffer",
    "LineNr",
    -- "Folded",
    -- "FoldColumn",
    -- "CursorLine",
    -- "CursorLineNr",
    -- "VertSplit",
    "StatusLine",
    "StatusLineNC",
    "WinSeparator",
    "TabLine",
    "TabLineFill",
    "TabLineSel",
    "Pmenu",
    "PmenuSel",
    "PmenuSbar",
    "PmenuThumb",
    "FloatBorder",
    "FloatTitle",
    "NormalSB",
    "TelescopeNormal",
    "TelescopeBorder",
    "TelescopePromptNormal",
    "TelescopePromptBorder",
    "TelescopeResultsNormal",
    "TelescopeResultsBorder",
    "TelescopePreviewNormal",
    "TelescopePreviewBorder",
    -- "Visual",
    -- "VisualNOS",
    -- "MatchParen",
    "Search",
    "IncSearch",
    "ColorColumn",
    "Whitespace",
    "NonText",
    "SpecialKey",
    "NvimTreeNormal",
    "NvimTreeNormalNC",
    "NvimTreeEndOfBuffer",
    "NvimTreeVertSplit",
    "NeoTreeNormal",
    "NeoTreeNormalNC",
    "NeoTreeFloatBorder",
    "DiagnosticSignError",
    "DiagnosticSignWarn",
    "DiagnosticSignInfo",
    "DiagnosticSignHint",
    "LspInfoBorder",
    "MasonNormal",
    "NoiceCmdlinePopup",
    "NoicePopupBorder",
    "LazyNormal",
    "LazyButton",
    "LazyButtonActive",
    "DashboardHeader",
    "DashboardFooter",
    "DashboardCenter",
})

vim.api.nvim_create_user_command("TransparencyToggle", Transparency, {})
